#!/bin/bash
grep -q '^setParameter = textSearchEnabled=true' $OPENSHIFT_MONGODB_DIR/conf/mongodb.conf || echo -e '\nsetParameter = textSearchEnabled=trueq' >> $OPENSHIFT_MONGODB_DIR/conf/mongodb.conf
